apiVersion: apps/v1
kind: Deployment
metadata:
  name: psp-sec-mock
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    spec:
      restartPolicy: Always
      containers:
        - name: psp-sec-mock
          image: psp-sec-mock-image
          imagePullPolicy: Always
          ports:
            - name: psp-sec-mock
              containerPort: 8091
              protocol: TCP
          resources:
            requests:
              memory: 1Gi
              cpu: 300m
            limits:
              memory: 2Gi
              cpu: 400m
      imagePullSecrets:
            - name: regcred
      nodeSelector:
        envnodopa: sit-uat
      tolerations:
      - key: "envnodopa"
        operator: "Equal"
        value: "sit-uat"
        effect: "NoExecute"              
