pr: none
trigger: none
pool:
  vmImage: 'ubuntu-latest'
parameters:
  - name: env
    displayName: Environment to deploy
    type: string
    values:
      - dev
      - sit
variables:
  repository_primary: 'mock-psp-primary' 
  repository_secondary: 'mock-psp-secondary' 
  dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
  kustomizeFolderApp: '$(Build.SourcesDirectory)/kustomize-mock-psp'
  mock_psp_primary_var: 'mock-psp-primary'
  mock_psp_secondary_var: 'mock-psp-secondary'

stages:
  - stage: retrieve_info
    displayName: "Retrieve info (${{ parameters.env }})"
    jobs:
      - job: retrieve_info
        displayName: "Retrieve info (${{ parameters.env }})"
        steps:
          - checkout: self
            clean: true
            persistCredentials: true
          - script: |
              APP_VERSION=$(jq -r .version package.json)
              echo "##vso[task.setvariable variable=APP_VERSION;isOutput=true]$APP_VERSION"
            displayName: Set version
            name: getVar
            
  - stage: build_mock_psp_primary
    displayName: "Build MOCK_PSP_PRIMARY (${{ parameters.env }})"
    condition: succeeded()
    dependsOn:
      - retrieve_info
    variables:
      - group: nodo-integration-test-${{ parameters.env }}
      - name: appVersion
        value: $[ stageDependencies.retrieve_info.retrieve_info.outputs['getVar.APP_VERSION'] ]
    jobs:
      - job: build_npm_mock_psp_primary
        displayName: 'build stage for MOCK_PSP_PRIMARY'
        steps:
        - task: NodeTool@0
          inputs:
            versionSpec: '16.x'
          displayName: 'Install Node.js - MOCK_PSP_PRIMARY'
        - script: |
            npm install --legacy-peer-deps
          displayName: 'npm install - MOCK_PSP_PRIMARY'
        - script: |
            npm run generate build
            pwd
            ls -lrt
          displayName: 'npm build - MOCK_PSP_PRIMARY'
        - script: |
            cp .nexi.env .env
          displayName: 'Copy env - MOCK_PSP_PRIMARY'
        - task: Docker@2
          displayName: 'Build and push image - MOCK_PSP_PRIMARY'
          inputs:
              containerRegistry: $(container-registry-service-connection-${{ parameters.env }})
              repository: $(repository_primary)
              command: 'buildAndPush'
              Dockerfile: $(dockerfile)
              tags: $(appVersion)
              
              
  - stage: build_mock_PSP_secondary
    displayName: "Build MOCK_PSP_SECONDARY (${{ parameters.env }})"
    condition: succeeded()
    dependsOn:
      - retrieve_info
    variables:
      - group: nodo-integration-test-${{ parameters.env }}
      - name: appVersion
        value: $[ stageDependencies.retrieve_info.retrieve_info.outputs['getVar.APP_VERSION'] ]
    jobs:
      - job: build_npm_mock_psp_secondary
        displayName: 'build stage for MOCK_PSP_SECONDARY'
        steps:
        - task: NodeTool@0
          inputs:
            versionSpec: '16.x'
          displayName: 'Install Node.js - MOCK_PSP_SECONDARY'
        - script: |
            npm install --legacy-peer-deps
          displayName: 'npm install - MOCK_PSP_SECONDARY'
        - script: |
            npm run generate build
            pwd
            ls -lrt
          displayName: 'npm build - MOCK_PSP_SECONDARY'
        - script: |
            cp .nexi_sec.env .env
          displayName: 'Copy env - MOCK_PSP_SECONDARY'
        - task: Docker@2
          displayName: 'Build and push image - MOCK_PSP_SECONDARY'
          inputs:
              containerRegistry: $(container-registry-service-connection-${{ parameters.env }})
              repository: $(repository_secondary)
              command: 'buildAndPush'
              Dockerfile: $(dockerfile)
              tags: $(appVersion)


  - stage: push_manifest_mock_psp_primary
    displayName: "Push manifest MOCK_PSP_PRIMARY - (${{ parameters.env }})"
    condition: succeeded()
    dependsOn:
      - retrieve_info
      - build_mock_psp_primary
    variables:
      - group: nodo-integration-test-${{ parameters.env }}
      - name: appVersion  
        value: $[ stageDependencies.retrieve_info.retrieve_info.outputs['getVar.APP_VERSION'] ]
    jobs:
      - job: push_manifest_mock_psp_primary
        displayName: "Push manifest MOCK_PSP_PRIMARY - ${{ parameters.env }}"
        steps:
          - checkout: self
            clean: true
            persistCredentials: true
          - task: KubernetesManifest@0
            name: "bakeApp"
            inputs:
              action: "bake"
              renderType: 'kustomize'
              kustomizationPath: $(kustomizeFolderApp)/$(mock_psp_primary_var)/${{ parameters.env }}
              containers: $(repository-docker-${{ parameters.env }})/$(repository_primary):$(appVersion)
            displayName: "Create manifest MOCK_PSP_PRIMARY app (${{ parameters.env }})"
          - publish: $(bakeApp.manifestsBundle)
            displayName: "Publish manifest MOCK_PSP_PRIMARY app (${{ parameters.env }})"
            artifact: $(appVersion)-${{ parameters.env }}-$(repository_primary)-manifest-app-$(mock_psp_primary_var)

            
  - stage: deploy_mock_psp_primary
    displayName: "Deploy MOCK_PSP_PRIMARY - (${{ parameters.env }})"
    dependsOn:
      - retrieve_info
      - build_mock_psp_primary
      - push_manifest_mock_psp_primary
    variables:
      - group: nodo-integration-test-${{ parameters.env }}
      - name: appVersion
        value: $[ stageDependencies.retrieve_info.retrieve_info.outputs['getVar.APP_VERSION'] ]
    condition: succeeded()
    jobs:
      - job: deploy_mock_psp_primary
        displayName: "Deploy MOCK_PSP_PRIMARY - ${{ parameters.env }}"
        pool: $(deploy-pool-${{ parameters.env }})
        steps:
          - checkout: none
          - script: |
              ls -la $(Pipeline.Workspace)/$(appVersion)-${{ parameters.env }}-$(repository_primary)-manifest-app-$(mock_psp_primary_var)
              rm -rf $(Pipeline.Workspace)/$(appVersion)-${{ parameters.env }}-$(repository_primary)-manifest-app-$(mock_psp_primary_var)
            displayName: "Clean old cached files $(appVersion)-${{ parameters.env }}-$(repository_primary)-manifest-app-$(mock_psp_primary_var)"
          - download: current
            artifact: $(appVersion)-${{ parameters.env }}-$(repository_primary)-manifest-app-$(mock_psp_primary_var)
            displayName: "Download manifest $(repository_primary) app $(appVersion)-${{ parameters.env }}-$(repository_primary)-manifest-app-$(mock_psp_primary_var)"
          - task: KubernetesManifest@0
            displayName: "Deploy manifest for $(repository_primary) app"
            inputs:
              action: 'deploy'
              kubernetesServiceConnection:  $(kubernetes-service-connection-mock-psp-${{ parameters.env }})
              namespace: $(mock-psp-kubernetes-namespace-${{ parameters.env }})
              manifests: $(Pipeline.Workspace)/$(appVersion)-${{ parameters.env }}-$(repository_primary)-manifest-app-$(mock_psp_primary_var)/*.yaml


  - stage: push_manifest_mock_psp_secondary
    displayName: "Push manifest MOCK_PSP_SECONDARY - (${{ parameters.env }})"
    condition: succeeded()
    dependsOn:
      - retrieve_info
      - build_mock_psp_secondary
    variables:
      - group: nodo-integration-test-${{ parameters.env }}
      - name: appVersion  
        value: $[ stageDependencies.retrieve_info.retrieve_info.outputs['getVar.APP_VERSION'] ]
    jobs:
      - job: push_manifest_mock_psp_secondary
        displayName: "Push manifest MOCK_PSP_SECONDARY - ${{ parameters.env }}"
        steps:
          - checkout: self
            clean: true
            persistCredentials: true
          - task: KubernetesManifest@0
            name: "bakeApp"
            inputs:
              action: "bake"
              renderType: 'kustomize'
              kustomizationPath: $(kustomizeFolderApp)/$(mock_psp_secondary_var)/${{ parameters.env }}
              containers: $(repository-docker-${{ parameters.env }})/$(repository_secondary):$(appVersion)
            displayName: "Create manifest MOCK_PSP_SECONDARY) app (${{ parameters.env }})"
          - publish: $(bakeApp.manifestsBundle)
            displayName: "Publish manifest MOCK_PSP_SECONDARY app (${{ parameters.env }})"
            artifact: $(appVersion)-${{ parameters.env }}-$(repository_secondary)-manifest-app-$(mock_psp_secondary_var)

            
  - stage: deploy_mock_psp_secondary
    displayName: "Deploy MOCK_PSP_SECONDARY - (${{ parameters.env }})"
    dependsOn:
      - retrieve_info
      - build_mock_psp_secondary
      - push_manifest_mock_psp_secondary
    variables:
      - group: nodo-integration-test-${{ parameters.env }}
      - name: appVersion
        value: $[ stageDependencies.retrieve_info.retrieve_info.outputs['getVar.APP_VERSION'] ]
    condition: succeeded()
    jobs:
      - job: deploy_mock_psp_secondary
        displayName: "Deploy MOCK_PSP_SECONDARY - ${{ parameters.env }}"
        pool: $(deploy-pool-${{ parameters.env }})
        steps:
          - checkout: none
          - script: |
              ls -la $(Pipeline.Workspace)/$(appVersion)-${{ parameters.env }}-$(repository_secondary)-manifest-app-$(mock_psp_secondary_var)
              rm -rf $(Pipeline.Workspace)/$(appVersion)-${{ parameters.env }}-$(repository_secondary)-manifest-app-$(mock_psp_secondary_var)
            displayName: "Clean old cached files $(appVersion)-${{ parameters.env }}-$(repository_secondary)-manifest-app-$(mock_psp_secondary_var)"
          - download: current
            artifact: $(appVersion)-${{ parameters.env }}-$(repository_secondary)-manifest-app-$(mock_psp_secondary_var)
            displayName: "Download manifest $(repository_secondary) app $(appVersion)-${{ parameters.env }}-$(repository_secondary)-manifest-app-$(mock_psp_secondary_var)"
          - task: KubernetesManifest@0
            displayName: "Deploy manifest for $(repository_secondary) app"
            inputs:
              action: 'deploy'
              kubernetesServiceConnection:  $(kubernetes-service-connection-mock-psp-${{ parameters.env }})
              namespace: $(mock-psp-kubernetes-namespace-${{ parameters.env }})
              manifests: $(Pipeline.Workspace)/$(appVersion)-${{ parameters.env }}-$(repository_secondary)-manifest-app-$(mock_psp_secondary_var)/*.yaml