pr: none
trigger: none
pool:
  vmImage: 'ubuntu-latest'
parameters:
  - name: env
    displayName: Environment to deploy
    type: string
    values:
      - dev
      - sit
variables:
  repository: 'mock-psp'
  dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
  kustomizeFolderApp: '$(Build.SourcesDirectory)/kustomize-mock-psp'
  
stages:
  - stage: retrieve_info
    displayName: "Retrieve info (${{ parameters.env }})"
    jobs:
      - job: retrieve_info
        displayName: "Retrieve info (${{ parameters.env }})"
        steps:
          - checkout: self
            clean: true
            persistCredentials: true
          - script: |
              APP_VERSION=$(jq -r .version package.json)
              echo "Versione: $APP_VERSION"
              echo "##vso[task.setvariable variable=APP_VERSION;isOutput=true]$APP_VERSION"
            displayName: Set version
            name: getVar
  - stage: build
    displayName: "Build (${{ parameters.env }})"
    condition: succeeded()
    dependsOn:
      - retrieve_info
    variables:
      - group: nodo-integration-test-vg-${{ parameters.env }}
      - name: appVersion
        value: $[ stageDependencies.retrieve_info.retrieve_info.outputs['getVar.APP_VERSION'] ]
    jobs:
      - job: build_npm
        displayName: buildnpm
        steps:
        - task: NodeTool@0
          inputs:
            versionSpec: '16.x'
          displayName: 'Install Node.js'
        - script: |
            echo "VERSIONE: $appVersion"
            echo "Ver2: $[ stageDependencies.retrieve_info.retrieve_info.outputs['getVar.APP_VERSION'] ]"
            npm install --legacy-peer-deps
          displayName: 'npm install'
        - script: |
            npm run generate build
            pwd
            ls -lrt
          displayName: 'npm build'
        - script: |
            cp .nexi.env .env
          displayName: 'Copy env'
        - task: Docker@2
          displayName: 'Build and push image'
          inputs:
              containerRegistry: $(container-registry-service-connection-${{ parameters.env }})
              repository: $(repository)
              command: 'buildAndPush'
              Dockerfile: $(dockerfile)
              tags: $(appVersion)
   
  - stage: push_manifest
    displayName: "Push manifest (${{ parameters.env }})"
    condition: succeeded()
    dependsOn:
      - build
    variables:
      - group: nodo-integration-test-vg-${{ parameters.env }}
      - name: appVersion
        value: $[ stageDependencies.retrieve_info.retrieve_info.outputs['getVar.APP_VERSION'] ]
    jobs:
      - job: push_manifest
        displayName: "Push manifest ${{ parameters.env }}"
        steps:
          - checkout: self
            clean: true
            persistCredentials: true
          - task: KubernetesManifest@0
            name: "bakeApp"
            inputs:
              action: "bake"
              renderType: 'kustomize'
              kustomizationPath: $(kustomizeFolderApp)/${{ parameters.env }}
              containers: $(repository-docker-${{ parameters.env }})/$(repository):$(appVersion)
            displayName: "Create manifest app (${{ parameters.env }})"
          - publish: $(bakeApp.manifestsBundle)
            displayName: "Publish manifest app (${{ parameters.env }})"
            artifact: $(appVersion)-${{ parameters.env }}-manifest-app
