apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mock-sit

images:
  - name: psp-sec-mock-image
    newName: toolbox.sia.eu/docker-pagopa/mock-psp-secondary
    newTag: 1.6.11

resources:
  - ../base
  - route.yaml

generatorOptions:
  disableNameSuffixHash: true
