apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mock-sit

images:
  - name: psp-sec-mock-image
    newName: nodopasitregistry.azurecr.io/mock-psp-secondary
    newTag: 0.0.1

resources:
  - namespace.yaml
  - ingress.yaml
  - ../base

generatorOptions:
  disableNameSuffixHash: true
