apiVersion: v2
name: mock-psp-chart
description: Mock PSP
type: application
version: 0.0.1
appVersion: 0.0.1
dependencies:
  - name: microservice-chart
    version: 2.4.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
