basemock: &basemock
  namespace: "nodo"
  nameOverride: ""
  fullnameOverride: ""
  terminationGracePeriodSeconds: 140
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  image:
    repository: pagopadcommonacr.azurecr.io/pagopamockpspservice
    tag: "0.0.1"
    pullPolicy: Always
  readinessProbe:
    handlerType: tcpSocket
    tcpSocket:
      port: 8080
    initialDelaySeconds: 20
    periodSeconds: 10
  livenessProbe:
    handlerType: tcpSocket
    tcpSocket:
      port: 8080
    initialDelaySeconds: 30
    periodSeconds: 20
  deployment:
    create: true
  service:
    create: true
    type: ClusterIP
    ports:
      - 8080
  serviceAccount:
    create: false
  securityContext:
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - all
  resources:
    requests:
      memory: "1Gi"
      cpu: "300m"
    limits:
      memory: "2Gi"
      cpu: "400m"
  autoscaling:
    enable: true
    minReplica: 1
    maxReplica: 1
    pollingInterval: 10 # seconds
    cooldownPeriod: 50 # seconds
    triggers:
      - type: cpu
        metadata:
          type: Utilization
          value: "75"
      - type: memory
        metadata:
          type: Utilization
          value: "75"
  envConfig:
    TIMEOUT_DELAY: "5000"
    PPT_NODO: "/mock"
    PORT: "8080"
    CC_BANK_PRIMARY_EC: "IT96R0123454321000000012345"
    CC_BANK_SECONDARY_EC: "IT04O0100003245350008332100"
    TEST_DEBUG: "Y"
    AUX_DIGIT: "3"
  tolerations:
    - key: dedicated
      operator: Equal
      value: "nodo"
      effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: nodo
                operator: In
                values:
                  - "true"
mock-primary:
  !!merge <<: *basemock
  ingress:
    create: true
    host: "weudev.nodo.internal.dev.platform.pagopa.it"
    path: /mock-psp-replica(/|$)(.*)
    pathType: Prefix
    servicePort: 8080
    annotations:
      nginx.ingress.kubernetes.io/proxy-read-timeout: "130"
    proxyBodySize: 100m
    rewriteTarget: /$2

mock-secondary:
  !!merge <<: *basemock
  ingress:
    create: true
    host: "weudev.nodo.internal.dev.platform.pagopa.it"
    path: /mock-psp-secondary-replica(/|$)(.*)
    pathType: Prefix
    servicePort: 8080
    annotations:
      nginx.ingress.kubernetes.io/proxy-read-timeout: "130"
    proxyBodySize: 100m
    rewriteTarget: /$2